class CfgPatches
{
	class Landrover
	{
		units[]={};
		weapons[]= {};
		requiredVersion	= 0.1;
		requiredAddons[]= 
		{
			"DZ_Data",
			"DZ_Vehicles_Wheeled",
			"DZ_Vehicles_Parts"
		};
	};
};
class CfgMods
{
	class Landrover
	{
		dir="Landrover";
		picture="";
		action="";
		hideName=1;
		hidePicture=1;
		name="Landrover";
		credits="Tyson";
		author="Tyson";
		authorID="0";
		version="1.0";
		extra=0;
		type="mod";
		dependencies[]=
		{
			"Game",
			"World",
			"Mission"
		};
		class defs
		{
			class gameScriptModule
			{
				value="";
				files[]=
				{
					"Landrover/scripts/3_Game"
				};
			};
			class worldScriptModule
			{
				value="";
				files[]=
				{
					"Landrover/scripts/4_World"
				};
			};
			class missionScriptModule
			{
				value="";
				files[]=
				{
					"Landrover/scripts/5_Mission"
				};
			};
		};
	}; 
};
class CfgVehicles
{
	class CarDoor;
	class Landrover_Driver_Door: CarDoor
	{
		scope=2;
		displayName="Landrover Driver Door";
		descriptionShort="Landrover Driver Door";
		Model = "\Landrover\proxy\Landrover_Driver_Door.p3d";
		weight=15000;
		itemSize[]={10,10};
		itemBehaviour=0;
		inventorySlot="Landrover_Driver_Door";
		rotationFlags=8;
		physLayer="item_large";
		hiddenSelections[]=
		{
			"base",
			"special"
		};
		hiddenSelectionsTextures[]=
		{
			"Landrover\data\lr_base_acr_co.paa",
			"Landrover\data\lr_special_acr_co.paa"
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=500;
					healthLevels[]=
					{						
						{
							1.00,							
							{}
						},						
						{
							0.69999999,
							{}
						},						
						{
							0.50,							
							{}
						},						
						{
							0.30000001,
							{}
						},						
						{
							0.0,							
							{}
						}
					};
				};
			};
			class DamageZones
			{
				class Window
				{
					class Health
					{
						hitpoints=150;
						healthLevels[]=
						{
							{
								1.00,							
								{
									"Landrover\data\lr_glass.rvmat"
								}
							},						
							{
								0.69999999,
								{
									"Landrover\data\lr_glass.rvmat"
								}
							},						
							{
								0.50,							
								{
									"Landrover\data\lr_glass_damage.rvmat"
								}
							},						
							{
								0.30000001,
								{
									"Landrover\data\lr_glass_destruct.rvmat"
								}
							},						
							{
								0.0,							
								
								"hidden"
							}
						};
					};
					fatalInjuryCoef=-1;
					inventorySlots[]={};
					transferToGlobalCoef=0;
					componentNames[]=
					{
						"dmgZone_doorWindow"
					};
				};
				class Doors
				{
					class Health
					{
						hitpoints=500;
						transferToGlobalCoef=1;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat",
									"Landrover\data\lr_special_destruct.rvmat"
								}
							}
						};
					};
					fatalInjuryCoef=-1;
					inventorySlots[]={};
					componentNames[]=
					{
						"dmgZone_doors"
					};
				};
			};
		};
	};
	class Landrover_CoDriver_Door: CarDoor
	{
		scope=2;
		displayName="Landrover CoDriver Door";
		descriptionShort="Landrover CoDriver Door";
		Model = "\Landrover\proxy\Landrover_CoDriver_Door.p3d";
		weight=15000;
		itemSize[]={10,10};
		itemBehaviour=0;
		inventorySlot="Landrover_CoDriver_Door";
		rotationFlags=8;
		physLayer="item_large";
		hiddenSelections[]=
		{
			"base",
			"special"
		};
		hiddenSelectionsTextures[]=
		{
			"Landrover\data\lr_base_acr_co.paa",
			"Landrover\data\lr_special_acr_co.paa"
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=500;
					healthLevels[]=
					{						
						{
							1.00,							
							{
							}
						},						
						{
							0.69999999,
							{
							}
						},						
						{
							0.50,
							
							{
							}
						},						
						{
							0.30000001,
							{
							}
						},						
						{
							0.00,
							
							{
							}
						}
					};
				};
			};
			class DamageZones
			{
				class Window
				{
					class Health
					{
						hitpoints=150;
						healthLevels[]=
						{
							{
								1.00,							
								{
									"Landrover\data\lr_glass.rvmat"
								}
							},						
							{
								0.69999999,
								{
									"Landrover\data\lr_glass.rvmat"
								}
							},						
							{
								0.50,							
								{
									"Landrover\data\lr_glass_damage.rvmat"
								}
							},						
							{
								0.30000001,
								{
									"Landrover\data\lr_glass_destruct.rvmat"
								}
							},						
							{
								0.0,							
								
								"hidden"
							}
						};
					};
					fatalInjuryCoef=-1;
					inventorySlots[]={};
					transferToGlobalCoef=0;
					componentNames[]=
					{
						"dmgZone_doorWindow"
					};
				};
				class Doors
				{
					class Health
					{
						hitpoints=500;
						transferToGlobalCoef=1;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat",
									"Landrover\data\lr_special_destruct.rvmat"
								}
							}
						};
					};
					fatalInjuryCoef=-1;
					inventorySlots[]={};
					componentNames[]=
					{
						"dmgZone_doors"
					};
				};
			};
		};
	};
	class Landrover_Hood: CarDoor
	{
		scope=2;
		displayName="Landrover Hood";
		descriptionShort="Landrover Hood";
		Model = "\Landrover\proxy\Landrover_Hood.p3d";
		weight=15000;
		itemSize[]={10,10};
		itemBehaviour=0;
		inventorySlot="Landrover_Hood";
		rotationFlags=0;
		physLayer="item_large";
		hiddenSelections[]=
		{
			"base"
		};
		hiddenSelectionsTextures[]=
		{
			"Landrover\data\lr_base_acr_co.paa"
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=500;
					healthLevels[]=
					{
						{
							1.00,
							{
								"Landrover\data\lr_base.rvmat"
							}
						},							
						{
							0.69999999,
							{
								"Landrover\data\lr_base.rvmat"
							}
						},							
						{
							0.50,
							{
								"Landrover\data\lr_base_damage.rvmat"
							}
						},							
						{
							0.30000001,
							{
								"Landrover\data\lr_base_damage.rvmat"
							}
						},							
						{
							0.00,
							{
								"Landrover\data\lr_base_destruct.rvmat"
							}
						}
					};
				};
				componentNames[]=
				{
					"dmgZone_doors"
				};
			};
		};
	};
	class Landrover_Trunk: CarDoor
	{
		scope=2;
		displayName="Landrover Cargo1";
		descriptionShort="Landrover Cargo1";
		Model = "\Landrover\proxy\Landrover_Trunk.p3d";
		weight=15000;
		itemSize[]={10,10};
		itemBehaviour=0;
		inventorySlot="Landrover_Trunk";
		rotationFlags=8;
		physLayer="item_large";
		hiddenSelections[]=
		{
			"base"
		};
		hiddenSelectionsTextures[]=
		{
			"Landrover\data\lr_base_acr_co.paa"
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=500;
					healthLevels[]=
					{
						{
							1.00,
							{
								"Landrover\data\lr_base.rvmat"
							}
						},							
						{
							0.69999999,
							{
								"Landrover\data\lr_base.rvmat"
							}
						},							
						{
							0.50,
							{
								"Landrover\data\lr_base_damage.rvmat"
							}
						},							
						{
							0.30000001,
							{
								"Landrover\data\lr_base_damage.rvmat"
							}
						},							
						{
							0.00,
							{
								"Landrover\data\lr_base_destruct.rvmat"
							}
						}
					};
				};
				componentNames[]=
				{
					"dmgZone_doors"
				};
			};
		};
	};
	class CarWheel;
	class Landrover_Wheel: CarWheel
	{
		scope=2;
		displayName="Landrover Wheel";
		descriptionShort="Landrover Wheel";
		model="\Landrover\proxy\Landrover_Wheel.p3d";
		weight=15000;
	    inventorySlot[]=
		{
			"Landrover_Wheel_1_1",
		    "Landrover_Wheel_1_2",
			"Landrover_Wheel_2_1",
			"Landrover_Wheel_2_2",
			"Landrover_Sparewheel"
		};
		rotationFlags=8;
		repairableWithKits[]={6};
		repairCosts[]={30};
		radiusByDamage[]={0,0.451,0.30000001,0.30000001,0.99980003,0.25,0.99989998,0.2};
		radius=0.451;
		width=0.142;
		tyreOffroadResistance=0.75;
		tyreGrip=0.80000001;
		tyreRollResistance=0.015;
		hiddenSelections[]=
		{
			"base"
		};
		hiddenSelectionsTextures[]=
		{
			"Landrover\data\lr_base_acr_co.paa"
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=400;
					healthLevels[]=
					{
						{
							1.00,
							{
								"Landrover\data\lr_base.rvmat"
							}
						},							
						{
							0.69999999,
							{
								"Landrover\data\lr_base.rvmat"
							}
						},							
						{
							0.50,
							{
								"Landrover\data\lr_base_damage.rvmat"
							}
						},							
						{
							0.30000001,
							{
								"Landrover\data\lr_base_damage.rvmat"
							}
						},							
						{
							0.00,
							{
								"Landrover\data\lr_base_destruct.rvmat"
							}
						}
					};
				};
			};
		};
    };
	class Landrover_Wheel_Ruined: CarWheel
	{
		scope=2;
		displayName="Landrover Wheel";
		descriptionShort="Landrover Wheel";
		model="\Landrover\proxy\Landrover_Wheel_Ruined.p3d";
		weight=10000;
		inventorySlot[]=
		{
			"Landrover_Wheel_1_1",
		    "Landrover_Wheel_1_2",
			"Landrover_Wheel_2_1",
			"Landrover_Wheel_2_2",
			"Landrover_Sparewheel"
		};
		rotationFlags=8;
		radius=0.2;
		width=0.107;
		tyreOffroadResistance=0.1;
		tyreGrip=0.2;
		tyreRollResistance=0.30000001;
		hiddenSelections[]=
		{
			"base"
		};
		hiddenSelectionsTextures[]=
		{
			"Landrover\data\lr_base_acr_co.paa"
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=100;
					healthLevels[]=
					{
						{
							1.00,
							{}
						},							
						{
							0.69999999,
							{}
						},							
						{
							0.50,
							{}
						},							
						{
							0.30000001,
							{}
						},							
						{
							0.00,
							{}
						}
					};
				};
			};
		};
	};
	class Carscript;
	class Landrover_Base :Carscript
	{
	    scope=0;
        displayname="Landrover Base";
        Model="\Landrover\Landrover.p3d";
		hiddenSelections[]=
		{
		    "light_left",
			"light_right",
			"light_brake_1_2",
			"light_brake_2_2",
			"light_reverse_1_2",
			"light_reverse_2_2",
			"light_1_2",
			"light_2_2",
			"light_dashboard",
			"base",
			"special"
		};
		hiddenSelectionsTextures[]=
		{
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"Landrover\data\lr_base_acr_co.paa",
			"Landrover\data\lr_special_acr_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"Landrover\data\lr_base.rvmat",
			"Landrover\data\lr_special.rvmat"
		};
		frontReflectorMatOn="Landrover\data\landrover_front_lights_on.rvmat";
        frontReflectorMatOff="Landrover\data\lr_base.rvmat";
		brakeReflectorMatOn="Landrover\data\landrover_brake_lights_on.rvmat";
        brakeReflectorMatOff="Landrover\data\lr_base.rvmat";
		TailReflectorMatOn="Landrover\data\landrover110_tail_lights_on.rvmat";
	    TailReflectorMatOff="Landrover\data\lr_base.rvmat";
		ReverseReflectorMatOn="Landrover\data\landrover_reverse_lights_on.rvmat";
	    ReverseReflectorMatOff="Landrover\data\lr_base.rvmat";
		dashboardMatOn="Landrover\data\landrover_dashboard_lights_on.rvmat";
	    dashboardMatOff="Landrover\data\lr_base.rvmat";
		fuelCapacity=65;
		fuelConsumption=15;
	 	attachments[]=
		{
			"CarBattery",
			"Reflector_1_1",
			"Reflector_2_1",
			"CarRadiator",
			"SparkPlug",
			"Landrover_Driver_Door",
			"Landrover_CoDriver_Door",
			"Landrover_Hood",
			"Landrover_Trunk",
			"Landrover_Wheel_1_1",
		    "Landrover_Wheel_1_2",
			"Landrover_Wheel_2_1",
			"Landrover_Wheel_2_2",
			"Landrover_Sparewheel"
		};
	    class Crew
		{
			class Driver
			{
				actionSel="seat_driver";
				proxyPos="CrewDriver";
				getInPos="pos_driver";
				getInDir="pos_driver_dir";
				isDriver=1;
			};
			class CoDriver
			{
				actionSel="seat_codriver";
				proxyPos="CrewCoDriver";
				getInPos="pos_codriver";
				getInDir="pos_codriver_dir";
			};
			class Cargo1
			{
				actionSel="seat_cargo1";
				proxyPos="CrewCargo1";
			    getInPos="pos_cargo";
				getInDir="pos_cargo_dir";
			};
			class Cargo2
			{
				actionSel="seat_cargo2";
				proxyPos="CrewCargo2";
				getInPos="pos_cargo";
				getInDir="pos_cargo_dir";
			};
			class Cargo3
			{
				actionSel="seat_cargo3";
				proxyPos="CrewCargo3";
				getInPos="pos_cargo";
				getInDir="pos_cargo_dir";
            };
			class Cargo4
			{
				actionSel="seat_cargo4";
				proxyPos="CrewCargo4";
				getInPos="pos_cargo";
				getInDir="pos_cargo_dir";
            };
			class Cargo5
			{
				actionSel="seat_cargo5";
				proxyPos="CrewCargo5";
				getInPos="pos_cargo";
				getInDir="pos_cargo_dir";
            };
			class Cargo6
			{
				actionSel="seat_cargo6";
				proxyPos="CrewCargo6";
				getInPos="pos_cargo";
				getInDir="pos_cargo_dir";
            };
        };
		class GUIInventoryAttachmentsProps
		{
			class Engine
			{
				name="$STR_attachment_Engine0";
				description="";
				icon="set:dayz_inventory image:cat_vehicle_engine";
				attachmentSlots[]=
				{
					"CarBattery",
					"CarRadiator",
					"SparkPlug"
				};
			};
			class Body
			{
				name="$STR_attachment_Body0";
				description="";
				icon="set:dayz_inventory image:cat_vehicle_body";
				attachmentSlots[]=
				{
					"Reflector_1_1",
					"Reflector_2_1",
				    "Landrover_Driver_Door",
					"Landrover_CoDriver_Door",
					"Landrover_Hood",
					"Landrover_Trunk",
					"Landrover_Sparewheel"
				};
			};
			class Chassis
			{
				name="$STR_attachment_Chassis0";
				description="";
				icon="set:dayz_inventory image:cat_vehicle_chassis";
				attachmentSlots[]=
				{
					"Landrover_Wheel_1_1",
					"Landrover_Wheel_1_2",
					"Landrover_Wheel_2_1",
					"Landrover_Wheel_2_2"
				};
			};
		};
		class Cargo
		{
			itemsCargoSize[]={10,50};
			allowOwnedCargoManipulation=1;
			openable=0;
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints=2500;
					healthLevels[]=
					{
						{
							1.00,
							{
								
							}
						},						
						{
							0.69999999,
							{
								
							}
						},						
						{
							0.50,
							{
								
							}
						},						
						{
							0.30000001,
							{
								
							}
						},						
						{
							0.00,
							{
								
							}
						}
					};
				};
			};
			class DamageZones
			{
				class Chassis
				{
					class Health
					{
						hitpoints=2500;
						transferToGlobalCoef=0;
					};
					displayName="$STR_CfgVehicleDmg_Chassis0";
					memoryPoints[]=
					{
						"dmgZone_chassis"
					};
					componentNames[]=
					{
						"dmgZone_chassis"
					};
					transferToZonesNames[]=
					{
					};
					transferToZonesThreshold[]={};
					transferToZonesCoefs[]={};
					fatalInjuryCoef=-1;
					inventorySlots[]={};
				};
				class Front
				{
					class Health
					{
						hitpoints=2500;
						transferToGlobalCoef=0;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat",
									"Landrover\data\lr_special_destruct.rvmat"
								}
							}
						};
					};
					displayName="$STR_CfgVehicleDmg_Bumper0";
					transferToZonesNames[]=
					{
						"Reflector_1_1",
						"Reflector_2_1",
						"Fender_1_1",
						"Fender_2_1",
						"Engine"
					};
					transferToZonesCoefs[]={0.1,0.1,0.1,0.1,0.15};
					memoryPoints[]=
					{
						"dmgZone_front"
					};
					componentNames[]=
					{
						"dmgZone_front"
					};
					fatalInjuryCoef=-1;
					inventorySlots[]=
					{
						"Landrover_Hood",
						"CarRadiator",
						"Landrover_Wheel_1_1",
						"Landrover_Wheel_2_1"
					};
					inventorySlotsCoefs[]={0.3,0.25,0.1,0.1};
				};
				class Back
				{
					class Health
					{
						hitpoints=2500;
						transferToGlobalCoef=0;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat"
								}
							}
						};
					};
					displayName="$STR_CfgVehicleDmg_Bumper0";
					transferToZonesNames[]=
					{
						"Fender_1_2",
						"Fender_2_2"
					};
					transferToZonesCoefs[]={0.15,0.15};
					memoryPoints[]=
					{
						"dmgZone_back"
					};
					componentNames[]=
					{
						"dmgZone_back"
					};
					fatalInjuryCoef=-1;
					inventorySlots[]=
					{
						"Landrover_Trunk",
						"Landrover_Wheel_1_2",
						"Landrover_Wheel_2_2"
					};
					inventorySlotsCoefs[]={0.4,0.1,0.1};
				};
				class Roof
				{
					class Health
					{
						hitpoints=2500;
						transferToGlobalCoef=0;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_glass.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_glass.rvmat",
									"Landrover\data\lr_special.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_glass_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_glass_damage.rvmat",
									"Landrover\data\lr_special_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_glass_destruct.rvmat",
									"Landrover\data\lr_special_destruct.rvmat"
								}
							}
						};
					};
					displayName="$STR_CfgVehicleDmg_BackTarp0";
					memoryPoints[]=
					{
						"dmgZone_tarp"
					};
					componentNames[]=
					{
						"dmgZone_tarp"
					};
					fatalInjuryCoef=-1;
					inventorySlots[]={};
				};
				class Fender_1_1
				{
					class Health
					{
						hitpoints=1500;
						transferToGlobalCoef=0;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat"
								}
							}
						};
					};
					displayName="$STR_CfgVehicleDmg_Fender0";
					transferToZonesNames[]=
					{
						"Front",
						"Reflector_1_1",
						"Engine"
					};
					transferToZonesCoefs[]={0.1,0.05,0.08};
					memoryPoints[]=
					{
						"dmgZone_fender_1_1"
					};
					componentNames[]=
					{
						"dmgZone_fender_1_1"
					};
					fatalInjuryCoef=-1;
					inventorySlots[]=
					{
						"Landrover_Hood",
						"Landrover_Wheel_1_1",
						"Landrover_Driver_Door"
					};
					inventorySlotsCoefs[]={0.15,0.1,0.1};
				};
				class Fender_2_1: Fender_1_1
				{
					transferToZonesNames[]=
					{
						"Front",
						"Reflector_2_1",
						"Engine"
					};
					transferToZonesCoefs[]={0.3,0.3,0.6};
					memoryPoints[]=
					{
						"dmgZone_fender_2_1"
					};
					componentNames[]=
					{
						"dmgZone_fender_2_1"
					};
					inventorySlots[]=
					{
						"Landrover_Hood",
						"Landrover_Wheel_2_1",
						"Landrover_CoDriver_Door"
					};
				};
				class Fender_1_2: Fender_1_1
				{
					transferToZonesNames[]=
					{
						"Back"
					};
					transferToZonesCoefs[]={0.15};
					memoryPoints[]=
					{
						"dmgZone_fender_1_2"
					};
					componentNames[]=
					{
						"dmgZone_fender_1_2"
					};
					inventorySlots[]=
					{
						"Landrover_Trunk",
						"Landrover_Wheel_1_2"
					};
					inventorySlotsCoefs[]={0.2,0.1};
				};
				class Fender_2_2: Fender_1_1
				{
					transferToZonesNames[]=
					{
						"Back",
						"FuelTank"
					};
					transferToZonesCoefs[]={0.15,0.2};
					memoryPoints[]=
					{
						"dmgZone_fender_2_2"
					};
					componentNames[]=
					{
						"dmgZone_fender_2_2"
					};
					inventorySlots[]=
					{
						"Landrover_Trunk",
						"Landrover_Wheel_2_2"
					};
					inventorySlotsCoefs[]={0.2,0.1};
				};
				class WindowFront
				{
					class Health
					{
						hitpoints=200;
						transferToGlobalCoef=0;
						healthLevels[]=
						{
							{
								1.00,
								
								{
									"Landrover\data\lr_glass.rvmat"
								}
							},
							{
								0.69999999,
								{
									"Landrover\data\lr_glass.rvmat"
								}
							},
							{
								0.50,
								
								{
									"Landrover\data\lr_glass_damage.rvmat"
								}
							},
							{
								0.30000001,
								{									
									"Landrover\data\lr_glass_destruct.rvmat"
								}
							},
							{
								0.00,
							
									"hidden"
							
							}
						};
					};
					displayName="$STR_CfgVehicleDmg_Window0";
					memoryPoints[]=
					{
						"dmgZone_windowFront"
					};
					componentNames[]=
					{
						"dmgZone_windowFront"
					};
					fatalInjuryCoef=-1;
					inventorySlots[]={};
					inventorySlotsCoefs[]={};
				};
				class Engine
				{
					class Health
					{
						hitpoints=2000;
						transferToGlobalCoef=1;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat"
								}
							}
						};
					};
					displayName="$STR_CfgVehicleDmg_Engine0";
					memoryPoints[]=
					{
						"dmgZone_engine"
					};
					componentNames[]=
					{
						"dmgZone_engine"
					};
					fatalInjuryCoef=0.001;
					inventorySlots[]=
					{
						"CarBattery",
						"SparkPlug"
					};
					inventorySlotsCoefs[]={0.1,0.05};
				};
				class FuelTank
				{
					class Health
					{
						hitpoints=1000;
						transferToGlobalCoef=0;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat"
								}
							}
						};
					};
					componentNames[]=
					{
						"dmgZone_fuelTank"
					};
					displayName="$STR_CfgVehicleDmg_FuelTank0";
					fatalInjuryCoef=-1;
					inventorySlots[]={};
					inventorySlotsCoefs[]={};
				};
				class Reflector_1_1
				{
					class Health
					{
						hitpoints=100;
						transferToGlobalCoef=0;
						healthLevels[]=
						{
							{
								1.00,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.69999999,
								{
									"Landrover\data\lr_base.rvmat"
								}
							},							
							{
								0.50,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.30000001,
								{
									"Landrover\data\lr_base_damage.rvmat"
								}
							},							
							{
								0.00,
								{
									"Landrover\data\lr_base_destruct.rvmat"
								}
							}
						};
					};
					displayName="$STR_CfgVehicleDmg_Reflector0";
					memoryPoints[]=
					{
						"dmgZone_lights_1_1"
					};
					componentNames[]=
					{
						"dmgZone_lights_1_1"
					};
					fatalInjuryCoef=-1;
					transferToZonesNames[]=
					{
						"Front",
						"Fender_1_1"
					};
					transferToZonesCoefs[]={1,1};
					inventorySlots[]=
					{
						"Reflector_1_1",
						"Landrover_Wheel_1_1"
					};
					inventorySlotsCoefs[]={1,0.1};
				};
				class Reflector_2_1: Reflector_1_1
				{
					memoryPoints[]=
					{
						"dmgZone_lights_2_1"
					};
					componentNames[]=
					{
						"dmgZone_lights_2_1"
					};
					transferToZonesNames[]=
					{
						"Front",
						"Fender_2_1"
					};
					inventorySlots[]=
					{
						"Reflector_2_1",
						"Landrover_Wheel_2_1"
					};
				};
			};
		};
		class ObstacleGenerator
		{
			carve=1;
			timeToStationary=5;
			moveThreshold=0.5;
			class Shapes
			{
				class Cylindric
				{
					class Cyl1
					{
						radius=1;
						height=1.5;
						center[]={0,0,0.69999999};
					};
					class Cyl3
					{
						radius=1;
						height=1.5;
						center[]={0,0,-0.69999999};
					};
				};
			};
		};
        class SimulationModule
		{
			drive="DRIVE_AWD";
			class Steering
			{
				maxSteeringAngle=35;
				increaseSpeed[] = {0,45,60,25,100,15};
				decreaseSpeed[] = {0,90,60,45,100,15};
				centeringSpeed[] = {0,0,15,28,60,45,100,60};
			};
			class Throttle
			{
				reactionTime=0.25;
				defaultThrust=0.8;
				gentleThrust=0.6;
				turboCoef=5;
				gentleCoef=0.7;
			};
			class Brake
			{
				pressureBySpeed[]={0,0.85,10,0.7,20,0.5,40,0.4,60,0.43,80,0.46,100,0.52,120,0.7};
				reactionTime=0.25;
				driverless=0.1;
			};
			class Aerodynamics
			{
				frontalArea=2.18;
				dragCoefficient=0.65;
			};
			class Engine
			{
				torqueCurve[]={650,0,850,110,1200,150,2500,200,4350,160,7300,0};
				inertia=0.5;
				frictionTorque=160;
				rollingFriction=0.5;
				viscousFriction=0.5;
				rpmIdle=800;
				rpmMin=850;
				rpmClutch=1450;
				rpmRedline=6150;
			};
			class Clutch
			{
				maxTorqueTransfer=440;
				uncoupleTime=0.1;
				coupleTime=0.1;
			};
			class Gearbox
			{
				type="GEARBOX_MANUAL";
				reverse=3.91;
				ratios[]={3.6,3.0,2.3,1.45,1.0};
			};
			class CentralDifferential
			{
				ratio=1.5;
				type="DIFFERENTIAL_LOCKED";
			};
			class Axles
			{
				class Front
				{
					maxBrakeTorque=3500;
					maxHandbrakeTorque=4000;
					wheelHubMass=15;
					wheelHubRadius=0.284;
					class Differential
					{
						ratio=4.0;
						type="DIFFERENTIAL_OPEN";
					};
					class Suspension
					{
						stiffness=40000;
						compression=2100;
						damping=5400;
						travelMaxUp=0.10;
						travelMaxDown=0.06;
					};
					class Wheels
					{
						class Left
						{
							animTurn="turnfrontleft";
							animRotation="wheelfrontleft";
							wheelHub="wheel_1_1_damper_land";
							animDamper="damper_1_1";
							inventorySlot="Landrover_Wheel_1_1";
						};
						class Right
						{
							animTurn="turnfrontright";
							animRotation="wheelfrontright";
							wheelHub="wheel_2_1_damper_land";
							animDamper="damper_2_1";
							inventorySlot="Landrover_Wheel_2_1";
						};
					};
				};
				class Rear
				{
					maxBrakeTorque=1750;
					maxHandbrakeTorque=4000;
					wheelHubMass=15;
					wheelHubRadius=0.284;
					class Differential
					{
						ratio=4.0;
						type="DIFFERENTIAL_OPEN";
					};
					class Suspension
					{
						stiffness=40000;
						compression=2100;
						damping=5400;
						travelMaxUp=0.10;
						travelMaxDown=0.06;
					};
					class Wheels
					{
						class Left
						{
							animTurn="turnbackleft";
							animRotation="wheelbackleft";
							wheelHub="wheel_1_2_damper_land";
							animDamper="damper_1_2";
							inventorySlot="Landrover_Wheel_1_2";
						};
						class Right
						{
							animTurn="turnbacktright";
							animRotation="wheelbackright";
							wheelHub="wheel_2_2_damper_land";
							animDamper="damper_2_2";
							inventorySlot="Landrover_Wheel_2_2";
						};
					};
				};
			};
		};		
		class AnimationSources 
		{
			class DoorsDriver
			{
				source="user";
				initPhase=0;
				animPeriod=0.5;
			};
			class DoorsCoDriver: DoorsDriver
			{
			};
			class DoorsHood: DoorsDriver
			{
			};
			class DoorsTrunk: DoorsDriver
			{
			};
			class damper_1_1
			{
				source="user";
				initPhase=0.48570001;
				animPeriod=1;
			};
			class damper_2_1: damper_1_1
			{
			};
			class damper_1_2
			{
				source="user";
				initPhase=0.40020001;
				animPeriod=1;
			};
			class damper_2_2: damper_1_2
			{
			};
		};
		class Sounds
		{
			thrust=0.60000002;
			thrustTurbo=1;
			thrustGentle=0.30000001;
			thrustSmoothCoef=0.02;
			camposSmoothCoef=0.029999999;
			soundSetsFilter[]=
			{
				"offroad_Engine_Offload_Ext_Rpm1_SoundSet",
				"offroad_Engine_Offload_Ext_Rpm2_SoundSet",
				"offroad_Engine_Offload_Ext_Rpm3_SoundSet",
				"offroad_Engine_Offload_Ext_Rpm4_SoundSet",
				"offroad_Engine_Offload_Ext_Rpm5_SoundSet",
				"offroad_Engine_Ext_Rpm0_SoundSet",
				"offroad_Engine_Ext_Rpm1_SoundSet",
				"offroad_Engine_Ext_Rpm2_SoundSet",
				"offroad_Engine_Ext_Rpm3_SoundSet",
				"offroad_Engine_Ext_Rpm4_SoundSet",
				"offroad_Engine_Ext_Rpm5_SoundSet",
				"offroad_Engine_Ext_Broken_SoundSet",
				"offroad_Tires_rock_slow_Ext_SoundSet",
				"offroad_Tires_rock_fast_Ext_SoundSet",
				"offroad_Tires_grass_slow_Ext_SoundSet",
				"offroad_Tires_grass_fast_Ext_SoundSet",
				"offroad_Tires_gravel_slow_Ext_SoundSet",
				"offroad_Tires_gravel_fast_Ext_SoundSet",
				"offroad_Tires_gravel_dust_fast_Ext_SoundSet",
				"offroad_Tires_asphalt_slow_Ext_SoundSet",
				"offroad_Tires_asphalt_fast_Ext_SoundSet",
				"offroad_Tires_water_slow_Ext_SoundSet",
				"offroad_Tires_water_fast_Ext_SoundSet",
				"Offroad_skid_dirt_SoundSet",
				"offroad_dirt_turn_SoundSet",
				"offroad_Rain_Ext_SoundSet",
				"offroad_damper_left_SoundSet",
				"offroad_damper_right_SoundSet"
			};
			soundSetsInt[]=
			{
				"Offroad_Tires_Asphalt_Fast_General_Int_SoundSet",
				"Offroad_Wind_SoundSet"
			};
		};
	};
    class Landrover : Landrover_Base
	{
	    scope=2;
	};
};